//
//  UIColor+FIAdditions.swift
//
//  Generated by Zeplin on 8/29/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	@nonobjc class var fiRed: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 73.0 / 255.0, blue: 74.0 / 255.0, alpha: 1.0)
	}

    @nonobjc class var fiBlack: UIColor {
        return UIColor(red: 57.0 / 255.0, green: 57.0 / 255.0, blue: 57.0 / 255.0, alpha: 1.0)
    }

    
	@nonobjc class var fiOrange: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 153.0 / 255.0, blue: 31.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiGreen: UIColor {
		return UIColor(red: 20.0 / 255.0, green: 206.0 / 255.0, blue: 102.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiYellow: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 200.0 / 255.0, blue: 45.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiBlue: UIColor {
		return UIColor(red: 31.0 / 255.0, green: 182.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiLightText: UIColor {
		return UIColor(red: 61.0 / 255.0, green: 73.0 / 255.0, blue: 89.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiSlateGray: UIColor {
		return UIColor(red: 39.0 / 255.0, green: 48.0 / 255.0, blue: 57.0 / 255.0, alpha: 1.0)
	}
    
    @nonobjc class var fiBlueBar: UIColor {
        return UIColor(red: 73.0 / 255.0, green: 102.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }

	@nonobjc class var fiWhite: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiLightGray: UIColor { 
		return UIColor(white: 153.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiDarkBlueGrey: UIColor {
		return UIColor(red: 35.0 / 255.0, green: 53.0 / 255.0, blue: 70.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var fiPaleGrey: UIColor {
		return UIColor(red: 226.0 / 255.0, green: 232.0 / 255.0, blue: 244.0 / 255.0, alpha: 1.0)
	}
}
